# Generated by Django 2.1 on 2020-03-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='designation',
            field=models.CharField(default='SE', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Pune,India', max_length=200),
        ),
    ]
